# Generated by Django 5.2.7 on 2026-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product', verbose_name='تصویر محصول'),
        ),
    ]
