# Generated by Django 5.2.7 on 2026-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
