# Generated by Django 5.2.7 on 2026-04-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteModel',
            new_name='SiteSettings',
        ),
    ]
