# Generated by Django 5.2.7 on 2026-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('url_title', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
    ]
