# Generated by Django 5.2.7 on 2026-05-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_articlecategory_parents_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecategory',
            old_name='parents',
            new_name='parent',
        ),
    ]
